language: generic 

sudo: required
service :
  - docker

before_install:
 - docker build -t motmaen73/docker-react-f Dockerfile.dev .


script:

  - docker run -e CI=true motmaen73/docker-react npm run test
