

FROM node:alpine
WORKDIR '/app'
COPY package.json .
RUN mkdir -p node_modules/.cache && chmod -R 777 node_modules/.cache

RUN npm install
COPY . .
RUN npm run build


FROM nginx
COPY --from=0 /app/build /usr/share/nginx/html